org.gradle.jvmargs=-Xmx4096m -XX:+UseParallelGC -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configureondemand=true
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.incremental=true
kotlin.code.style=official
android.aapt2FromMavenOverride=/data/data/com.termux/files/usr/bin/aapt2

cloudinary.cloud_name=z06q7obd
cloudinary.upload_preset=school_manager_unsigned
org.gradle.daemon=true
