package com.school.manager.ui.navigation

object Routes {
    const val LOGIN = "login"
    const val OWNER_DASHBOARD = "owner_dashboard"
    const val FORGOT_PASSWORD = "forgot_password"
    const val SIGNUP = "signup"
    const val ADMIN_PENDING_USERS = "admin_pending_users"
    const val PROFILE = "profile"
    const val SETTINGS = "settings"
    const val ADMIN_BRANDING = "admin_branding"
    const val ADMIN_FEE_HEADS = "admin_fee_heads"
    const val ADMIN_INVOICES = "admin_invoices"
    const val ADMIN_NOTIFICATION_LOGS = "admin_notification_logs"
    const val ADMIN_PAYMENT_METHODS = "admin_payment_methods"
    const val FEEDBACK = "feedback"
    const val ABOUT = "about"
    const val CONTACT = "contact"
    const val NOTIFICATIONS = "notifications"
    const val STAFF_DIRECTORY = "staff_directory"
    const val TEACHER_TIMETABLE = "teacher_timetable"
    const val TEACHER_MY_CLASSES = "teacher_my_classes"
    const val TEACHER_FEES = "teacher_fees"
    const val TEACHER_HOMEWORK = "teacher_homework"
    const val TEACHER_LEAVE = "teacher_leave"
    const val TEACHER_NOTICES = "teacher_notices"
    const val TEACHER_MESSAGES = "teacher_messages"
    const val ALL_ENTRIES = "all_entries"
    const val GLOBAL_SEARCH = "global_search"

    const val ADMIN_DASHBOARD = "admin_dashboard"
    const val ADMIN_USERS = "admin_users"
    const val ADMIN_USER_FORM = "admin_user_form/{userId}"
    const val ADMIN_CLASSES = "admin_classes"
    const val ADMIN_CLASS_FORM = "admin_class_form/{classId}"
    const val ADMIN_CLASS_DETAIL = "admin_class_detail/{classId}"
    const val ADMIN_SUBJECT_FORM = "admin_subject_form/{classId}/{subjectId}"
    const val ADMIN_EXAMS = "admin_exams"
    const val ADMIN_EXAM_FORM = "admin_exam_form/{examId}"
    const val ADMIN_TIMETABLE = "admin_timetable"
    const val ADMIN_TIMETABLE_CLASS = "admin_timetable_class/{classId}"
    const val ADMIN_TIMETABLE_BULK = "admin_timetable_bulk/{classId}"
    const val ADMIN_ANALYTICS = "admin_analytics"
    const val ADMIN_FEES = "admin_fees"
    const val ADMIN_FEE_COLLECT = "admin_fee_collect"
    const val ADMIN_PAYROLL = "admin_payroll"
    const val ADMIN_TRANSPORT = "admin_transport"
    const val ADMIN_SCAN_ATTENDANCE = "admin_scan_attendance"
    const val ADMIN_EXAM_MARKS = "admin_exam_marks"
    const val ADMIN_QUESTION_PAPERS = "admin_question_papers"
    const val ADMIN_GRADE_SETTINGS = "admin_grade_settings"
    const val ADMIN_SUBJECTS = "admin_subjects"
    const val ADMIN_SYLLABUS = "admin_syllabus"
    const val ADMIN_ADMISSIONS = "admin_admissions"
    const val ADMIN_FAMILY_FEE_COLLECTION = "admin_family_fee_collection"
    const val ADMIN_RESULT_CARDS = "admin_result_cards"
    const val ADMIN_CERTIFICATES = "admin_certificates"
    const val ADMIN_SCHOOL_ASSETS = "admin_school_assets"
    const val ADMIN_NOTIFICATIONS_SMTP = "admin_notifications_smtp"
    const val ADMIN_LEAVE_REQUESTS = "admin_leave_requests"
    const val ADMIN_PARENT_ACCOUNTS = "admin_parent_accounts"
    const val ADMIN_REPORTS = "admin_reports"
    const val ADMIN_ROLES = "admin_roles"
    const val ADMIN_USERS_ACCESS = "admin_users_access"
    const val ADMIN_BRANCH = "admin_branch"
    const val ADMIN_MODULES = "admin_modules"
    const val ADMIN_AUDIT_LOG = "admin_audit_log"
    const val ADMIN_SYSTEM_UPDATES = "admin_system_updates"
    const val ADMIN_BACKUPS = "admin_backups"
    const val ADMIN_SUBSCRIPTION = "admin_subscription"
    const val ADMIN_SOFTWARE_UPDATES = "admin_software_updates"
    const val ADMIN_LIBRARY = "admin_library"
    const val ADMIN_EXPENSES = "admin_expenses"
    const val ADMIN_RECEIPTS = "admin_receipts"
    const val ADMIN_FEES_VOUCHERS = "admin_fee_vouchers"
    const val ADMIN_ATTENDANCE = "admin_attendance"
    const val ADMIN_STAFF_ATTENDANCE = "admin_staff_attendance"
    const val ADMIN_FAMILIES = "admin_families"
    const val ADMIN_STUDENTS_LIST = "admin_students_list"

    const val TEACHER_DASHBOARD = "teacher_dashboard"
    const val TEACHER_ATTENDANCE = "teacher_attendance"
    const val TEACHER_GRADEBOOK = "teacher_gradebook/{examId}"
    const val TEACHER_ASSIGNMENTS = "teacher_assignments"
    const val TEACHER_ASSIGNMENT_FORM = "teacher_assignment_form/{assignmentId}"

    const val STUDENT_DASHBOARD = "student_dashboard"
    const val STUDENT_RESULTS = "student_results"
    const val STUDENT_ATTENDANCE = "student_attendance"
    const val STUDENT_TIMETABLE = "student_timetable"
    const val STUDENT_ASSIGNMENTS = "student_assignments"
    const val STUDENT_REPORT_CARD = "student_report_card"
    const val HALL_TICKET = "hall_ticket/{examId}"
    const val SUBMISSION_VIEWER = "submission_viewer/{assignmentId}"

    const val PARENT_DASHBOARD = "parent_dashboard"
    const val PARENT_CHILDREN = "parent_children"
    const val PARENT_MESSAGES = "parent_messages"
    const val NOTICE_BOARD = "notice_board"
    const val FEES = "fees"
    const val CHAT_LIST = "chat_list"
    const val CHAT_ROOM = "chat_room/{chatId}"
    const val FEE_PAYMENT = "fee_payment/{feeId}"

    fun userForm(userId: String = "new") = "admin_user_form/$userId"
    fun classForm(classId: String = "new") = "admin_class_form/$classId"
    fun classDetail(classId: String) = "admin_class_detail/$classId"
    fun subjectForm(classId: String, subjectId: String = "new") = "admin_subject_form/$classId/$subjectId"
    fun examForm(examId: String = "new") = "admin_exam_form/$examId"
    fun gradebook(examId: String) = "teacher_gradebook/$examId"
    fun assignmentForm(assignmentId: String = "new") = "teacher_assignment_form/$assignmentId"
    fun chatRoom(chatId: String) = "chat_room/$chatId"
    fun feePayment(feeId: String) = "fee_payment/$feeId"
    fun adminTimetableClass(classId: String) = "admin_timetable_class/$classId"
    fun adminTimetableBulk(classId: String) = "admin_timetable_bulk/$classId"
    fun hallTicket(examId: String) = "hall_ticket/$examId"
    fun submissionViewer(assignmentId: String) = "submission_viewer/$assignmentId"
    const val ADMIN_FAMILIES_LIST = "admin_families_list"
    const val ADMIN_FAMILY_FORM = "admin_family_form/{familyId}"
    const val ADMIN_STAFF_LIST = "admin_staff_list"
    const val ADMIN_STAFF_FORM = "admin_staff_form/{staffId}"
}
